#  https://medium.com/@yohanesdwikiwitman/spring-boot-3-template-part-2-configuring-application-yml-d147b97c9d35
logging:
  level.root: error
  level.web: TRACE
  level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG


yaml:
  name: application.yml
  aliases:
    - properties.yml
    - env.yml

server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: /my_api
  compression:
    enabled: true
    min-response-size: 1024
  forward-headers-strategy : framework

spring:
#  application:
#    name:todo_list
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  banner:
    location: classpath:banner.txt
  profiles:
    active: ${PROFILE:local,dev}

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost:5432}/${DATABASE_NAME:test_db}?createDatabaseIfNotExist=true
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: ${HIKARI_POOL_SIZE:10}
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000

  jpa:
    hibernate:
      naming:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

token:
  jwt:
    secret: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
    access-period: 30m
    refresh-period: 30d



  #spring.application.name=todo_list
  #
  ## ????????? ??????????? ? ???? ??????
  #spring.datasource.url=jdbc:postgresql://localhost:5432/test_db
  #spring.datasource.username=postgres
  #spring.datasource.password=postgres
  #spring.datasource.driver-class-name=org.postgresql.Driver
  #
  ## ????????? Hibernate
  #spring.jpa.hibernate.ddl-auto=update
  #spring.jpa.show-sql=true
  #spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
  #
  ## ?????????????? ????????? Hibernate
  ## spring.jpa.properties.hibernate.format_sql=true
  ## spring.jpa.properties.hibernate.use_sql_comments=true
  #
  ## ????????? ???? ?????????? (???????????)
  #spring.datasource.hikari.maximum-pool-size=10
  #spring.datasource.hikari.minimum-idle=2
  #spring.datasource.hikari.idle-timeout=30000
  #spring.datasource.hikari.max-lifetime=600000
  
